version: '3'
services:
  # https://discuss.elastic.co/t/linking-kibana-and-elasticsearch-with-docker-compose/179040/4
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - 5601:5601

  # cUrl:
  # Invoke-RestMethod "http://localhost:9200/routerinfo/_bulk?pretty" 
  # -Method Post -ContentType 'application/x-ndjson' -InFile "kibana.json"